/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ErrorContainer: typeof import('./src/containers/error/ErrorContainer.vue')['default']
    HeaderComponent: typeof import('./src/components/header/HeaderComponent.vue')['default']
    HomeContainer: typeof import('./src/containers/home/HomeContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
